"""create_events_table_and_add_weights

Revision ID: 01b0af10e813
Revises: 1aa61eb9d799
Create Date: 2026-09-10 22:32:21.119533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b0af10e813'
down_revision: Union[str, Sequence[str], None] = '1aa61eb9d799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('item_or_batch_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('COLLECTION_CREATED', 'AGGREGATOR_RECEIVED', 'WEIGHT_VERIFIED', 'SORTED', 'RECYCLER_RECEIVED', 'PROCESSING_CONFIRMED', 'EPR_ELIGIBILITY_CREATED', 'EPR_CREDIT_CREATED', 'REWARD_CREATED', 'RISK_FLAGGED', 'HAZARD_REPORTED', name='eventtype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('client_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.add_column('items', sa.Column('verified_weight', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('received_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'received_weight')
    op.drop_column('items', 'verified_weight')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
