"""create_risk_flags_table

Revision ID: 030d96603221
Revises: 4a80bd0b1ada
Create Date: 2026-09-11 00:15:36.080862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030d96603221'
down_revision: Union[str, Sequence[str], None] = '4a80bd0b1ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'FLAGGED', 'MANUAL_REVIEW', 'CLEARED', 'REJECTED', name='riskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_flags_id'), 'risk_flags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_flags_id'), table_name='risk_flags')
    op.drop_table('risk_flags')
    # ### end Alembic commands ###
