"""create_pickup_batch_items

Revision ID: 1aa61eb9d799
Revises: 57a07192f531
Create Date: 2026-09-10 20:59:48.752679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa61eb9d799'
down_revision: Union[str, Sequence[str], None] = '57a07192f531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('client_transaction_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_transaction_id')
    )
    op.create_table('pickup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ASSIGNED', 'COLLECTED', name='pickupstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_requests_id'), 'pickup_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_pr_id'), 'pickup_requests', ['pr_id'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cb_id', sa.String(), nullable=False),
    sa.Column('pickup_request_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('parent_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['pickup_request_id'], ['pickup_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_cb_id'), 'batches', ['cb_id'], unique=True)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rl_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('declared_weight', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('photo_hash', sa.String(), nullable=True),
    sa.Column('hazard_status', sa.Enum('NO_HAZARD', 'SWOLLEN_BATTERY', 'DAMAGED_BATTERY', 'LEAKAGE', 'UNKNOWN', name='hazardstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_rl_id'), 'items', ['rl_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_rl_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_cb_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_pickup_requests_pr_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_id'), table_name='pickup_requests')
    op.drop_table('pickup_requests')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
