"""add_verification_fields_to_items

Revision ID: 39566144cc58
Revises: 6e75e2a8de53
Create Date: 2026-09-11 02:57:20.167915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39566144cc58'
down_revision: Union[str, Sequence[str], None] = '6e75e2a8de53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('verified_is_ewaste', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('verified_confidence', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('verified_category', sa.String(), nullable=True))
    op.add_column('items', sa.Column('verified_decision', sa.String(), nullable=True))
    op.add_column('items', sa.Column('verified_provider', sa.String(), nullable=True))
    op.add_column('items', sa.Column('verified_reason', sa.String(), nullable=True))
    op.add_column('items', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'verified_at')
    op.drop_column('items', 'verified_reason')
    op.drop_column('items', 'verified_provider')
    op.drop_column('items', 'verified_decision')
    op.drop_column('items', 'verified_category')
    op.drop_column('items', 'verified_confidence')
    op.drop_column('items', 'verified_is_ewaste')
    # ### end Alembic commands ###
