"""add upi_id to redemptions

Revision ID: be0b49cc4799
Revises: 39566144cc58
Create Date: 2026-09-11 04:28:46.315047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0b49cc4799'
down_revision: Union[str, Sequence[str], None] = '39566144cc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemptions', sa.Column('upi_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redemptions', 'upi_id')
    # ### end Alembic commands ###
